version: '3.9'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
      
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb
networks:
  app-network: