version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: ["mongod", "--bind_ip_all"]
    networks:
      - app-network
      
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb

networks:
  app-network:
